import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html=readFileSync('vl/public/index.html','utf8');
const login=readFileSync('vl/public/pilot-login.html','utf8');
const registry=readFileSync('vl/public/builder-registry.js','utf8');
assert.match(html,/Governed AI Software Factory/);
assert.match(html,/VL builds software[\s\S]*with proof/);
assert.match(html,/HUMAN-GATED/);
assert.match(html,/Human production approval/);
assert.match(html,/Controlled Development \/ Controlled Alpha/);
assert.match(html,/Broad Public Launch[^<]*HOLD/);
assert.match(html,/Natural Language Request[\s\S]*Rollback \+ Audit/);
assert.match(html,/payment activation and paid resource provisioning remain approval-gated/i);
assert.match(html,/Desktop \/ CLI \/ developer tools[\s\S]*PLANNED/);
assert.match(html,/\.\/pilot-login\.html/);
assert.doesNotMatch(html,/autonomous production (deployment|promotion)/i);
assert.doesNotMatch(html,/sb_publishable|service_role|supabase\.co/i);
assert.match(login,/vl_pilot_session_v2/);
assert.match(login,/\/auth\/v1\/token\?grant_type=password/);
assert.match(login,/\/auth\/v1\/signup/);
assert.match(login,/customer_accounts/);
assert.match(login,/Continue to Assisted Build/);
assert.doesNotMatch(login,/service[_-]?role|SUPABASE_SERVICE_ROLE_KEY|approve_production|promote_production|production_promotion_bypassed.?true/i);
for(const id of ['mobile-flutter-v1','gis-web-v1','web-react-v1','pwa-react-v1','api-service-v1']) assert.match(registry,new RegExp(id));
assert.match(registry,/TECHNICAL PASS AWAITING HUMAN APPROVAL/);
assert.doesNotMatch(registry,/workflow_run_id|artifact_id|supabase|secret/i);
console.log('public capability surface: PASS');
