import "jsr:@supabase/functions-js@2/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6.2.10";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ISS="https://token.actions.githubusercontent.com",AUD="vrs-specialized-cert-depth-v2",REPO="lundus88/fieldgis-reference",REF="refs/heads/main",WF="lundus88/fieldgis-reference/.github/workflows/vl-specialized-cert-depth-v2.yml@refs/heads/main";
const jwks=createRemoteJWKSet(new URL(`${ISS}/.well-known/jwks`)); const sb=createClient(U,K,{auth:{persistSession:false}});
const REQUIRED:Record<string,string[]>={"gis-web-v1":["static_analysis_pass","map_runtime_pass","gps_marker_pass","export_kml_pass"],"mobile-flutter-v1":["static_analysis_pass","test_pass","apk_build_pass","android_device_e2e_pass","gps_capture_pass"]};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
async function oidc(t:string){const {payload}=await jwtVerify(t,jwks,{issuer:ISS,audience:AUD,algorithms:["RS256"],clockTolerance:60}); const w=String(payload.job_workflow_ref||payload.workflow_ref||""); if(payload.repository!==REPO||payload.ref!==REF||w!==WF) throw new Error("OIDC identity not allowed"); return {run_id:String(payload.run_id||""),run_attempt:String(payload.run_attempt||"1"),sha:String(payload.sha||""),workflow_ref:w};}
Deno.serve(async req=>{if(req.method!=="POST")return J({error:"POST required"},405);const a=req.headers.get("authorization")||"";if(!a.startsWith("Bearer "))return J({error:"OIDC required"},401);try{const id=await oidc(a.slice(7));const b=await req.json();const builder=String(b.builder_key||"");const reqs=REQUIRED[builder];if(!reqs)return J({error:"builder not allowed",blocked:true},400);const passed=Array.isArray(b.passed_evidence)?b.passed_evidence.map(String).sort():[];if(JSON.stringify(passed)!==JSON.stringify([...reqs].sort()))return J({error:"evidence mismatch",blocked:true},400);const {data:runs,error:e}=await sb.from("factory_runs").select("id,project_id,input,created_at,state,target_environment,production_locked").eq("target_environment","staging").eq("production_locked",true).eq("state","awaiting_approval").order("created_at",{ascending:true});if(e)throw e;let target:any=null;for(const r of runs||[]){const input=r.input||{};if(input.builder_key!==builder||input.certification_depth_run!==true)continue;const {data:ev,error:ee}=await sb.from("builder_certification_evidence").select("evidence_type").eq("builder_key",builder).eq("factory_run_id",r.id).in("evidence_type",reqs);if(ee)throw ee;const have=new Set((ev||[]).map((x:any)=>String(x.evidence_type)));if(reqs.some(x=>!have.has(x))){target=r;break;}}if(!target)return J({ok:true,status:"no_work",builder_key:builder,identity:id});const uri=`https://github.com/${REPO}/actions/runs/${id.run_id}#attempt-${id.run_attempt}`;const rows=reqs.map(t=>({builder_key:builder,factory_run_id:target.id,project_id:target.project_id,evidence_type:t,evidence_status:"pass",evidence:{provider:"github_actions_oidc",source:"specialized_builder_depth_v2",github_run_id:id.run_id,github_run_attempt:id.run_attempt,github_sha:id.sha,workflow_ref:id.workflow_ref,runtime_tested:true},source_uri:uri}));const {error:ie}=await sb.from("builder_certification_evidence").insert(rows);if(ie)throw ie;const {data:cert,error:ce}=await sb.rpc("evaluate_builder_certification",{p_builder_key:builder,p_activate:false});if(ce)throw ce;return J({ok:true,status:"recorded",builder_key:builder,factory_run_id:target.id,certification:cert,identity:id});}catch(e){return J({error:String((e as Error).message||e),blocked:true},401);}});