-- Fix mobile factory dependency drift discovered by fresh certification on 2026-10-04.
-- The generated pubspec pinned maplibre_gl 0.27.0, which no longer resolves,
-- while the certified current dependency resolves at 0.27.1.
-- This reconciles the live generator into source without changing production authority.
CREATE OR REPLACE FUNCTION private.seed_factory_sources()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'private', 'public', 'extensions', 'pg_temp'
AS $function$
declare
  a public.app_specs%rowtype;
  v_builder text;
  v_title text;
  v_main text;
  v_manifest text;
  v_pubspec text;
  v_model text;
  v_store text;
  v_test text;
begin
  if new.run_type <> 'build' or new.target_environment='production' or new.production_locked is distinct from true or new.app_spec_id is null then return new; end if;
  select * into a from public.app_specs where id=new.app_spec_id;
  if not found or a.status <> 'approved' then return new; end if;

  v_builder := coalesce(nullif(new.input->>'builder_key',''), a.spec #>> '{selected_builder,builder_key}', a.spec #>> '{routing,selected_builder,builder_key}');
  v_title := left(regexp_replace(coalesce(a.title,'VL Generated App'),'[^A-Za-z0-9 _-]','','g'),80);

  if v_builder='mobile-flutter-v1' then
    v_pubspec := $yaml$name: vl_generated_app
description: Generated by VL Software Factory.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  geolocator: 14.0.3
  shared_preferences: 2.5.5
  maplibre_gl: 0.27.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
$yaml$;

    v_model := $dart$import 'dart:convert';

class FieldPoint {
  final String id;
  final String label;
  final double latitude;
  final double longitude;
  final double accuracyM;
  final DateTime capturedAt;
  const FieldPoint({required this.id,required this.label,required this.latitude,required this.longitude,required this.accuracyM,required this.capturedAt});
  Map<String,dynamic> toJson()=>{'id':id,'label':label,'latitude':latitude,'longitude':longitude,'accuracy_m':accuracyM,'captured_at':capturedAt.toUtc().toIso8601String()};
  factory FieldPoint.fromJson(Map<String,dynamic> j)=>FieldPoint(id:j['id'] as String,label:(j['label']??'Point') as String,latitude:(j['latitude'] as num).toDouble(),longitude:(j['longitude'] as num).toDouble(),accuracyM:(j['accuracy_m'] as num? ?? 0).toDouble(),capturedAt:DateTime.parse(j['captured_at'] as String));
}
String pointsToJson(List<FieldPoint> pts)=>jsonEncode(pts.map((p)=>p.toJson()).toList());
List<FieldPoint> pointsFromJson(String raw)=>(jsonDecode(raw) as List).map((e)=>FieldPoint.fromJson(Map<String,dynamic>.from(e as Map))).toList();
String pointsToCsv(List<FieldPoint> pts){
  final rows=<String>['label,latitude,longitude,accuracy_m,captured_at'];
  rows.addAll(pts.map((p)=>'${p.label.replaceAll(',', ' ')},${p.latitude},${p.longitude},${p.accuracyM},${p.capturedAt.toUtc().toIso8601String()}'));
  return rows.join('\n');
}
String pointsToKml(List<FieldPoint> pts)=>'<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>'+pts.map((p)=>'<Placemark><name>${p.label}</name><Point><coordinates>${p.longitude},${p.latitude},0</coordinates></Point></Placemark>').join()+'</Document></kml>';
$dart$;

    v_store := $dart$import 'package:shared_preferences/shared_preferences.dart';
import 'field_point.dart';

class OfflinePointStore {
  static const _key='vl_field_points_v1';
  Future<List<FieldPoint>> load() async {
    final prefs=await SharedPreferences.getInstance();
    final raw=prefs.getString(_key);
    if(raw==null || raw.isEmpty) return <FieldPoint>[];
    return pointsFromJson(raw);
  }
  Future<void> save(List<FieldPoint> pts) async {
    final prefs=await SharedPreferences.getInstance();
    await prefs.setString(_key,pointsToJson(pts));
  }
}
$dart$;

    v_main := format($dart$import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:maplibre_gl/maplibre_gl.dart';
import 'field_point.dart';
import 'offline_store.dart';

void main()=>runApp(const VLFieldApp());
class VLFieldApp extends StatelessWidget {
  const VLFieldApp({super.key});
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:%L,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.teal),home:const FieldHome());
}
class FieldHome extends StatefulWidget { const FieldHome({super.key}); @override State<FieldHome> createState()=>_FieldHomeState(); }
class _FieldHomeState extends State<FieldHome> {
  final _store=OfflinePointStore();
  final List<FieldPoint> _points=[];
  bool _busy=false;
  String _status='Ready';
  @override void initState(){super.initState();_restore();}
  Future<void> _restore() async { final p=await _store.load(); if(mounted)setState(()=>_points.addAll(p)); }
  Future<bool> _ensurePermission() async {
    if(!await Geolocator.isLocationServiceEnabled()){setState(()=>_status='Location service disabled');return false;}
    var p=await Geolocator.checkPermission();
    if(p==LocationPermission.denied)p=await Geolocator.requestPermission();
    if(p==LocationPermission.denied || p==LocationPermission.deniedForever){setState(()=>_status='Location permission denied');return false;}
    return true;
  }
  Future<void> _capture() async {
    if(_busy)return; setState(()=>_busy=true);
    try{
      if(!await _ensurePermission())return;
      final pos=await Geolocator.getCurrentPosition(locationSettings:const LocationSettings(accuracy:LocationAccuracy.high,timeLimit:Duration(seconds:20)));
      final p=FieldPoint(id:DateTime.now().microsecondsSinceEpoch.toString(),label:'P${(_points.length+1).toString().padLeft(3,'0')}',latitude:pos.latitude,longitude:pos.longitude,accuracyM:pos.accuracy,capturedAt:DateTime.now().toUtc());
      setState(()=>_points.insert(0,p)); await _store.save(_points); setState(()=>_status='Captured ${p.label} · ±${p.accuracyM.toStringAsFixed(1)} m');
    } catch(e){setState(()=>_status='Capture failed: $e');} finally {if(mounted)setState(()=>_busy=false);}
  }
  Future<void> _copy(String value,String kind) async { await Clipboard.setData(ClipboardData(text:value)); if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$kind copied to clipboard'))); }
  @override Widget build(BuildContext context)=>Scaffold(
    appBar:AppBar(title:const Text(%L)),
    body:Column(children:[
      Expanded(flex:3,child:MapLibreMap(styleString:'https://demotiles.maplibre.org/style.json',initialCameraPosition:const CameraPosition(target:LatLng(5.9804,116.0735),zoom:10),myLocationEnabled:true)),
      Padding(padding:const EdgeInsets.fromLTRB(12,8,12,4),child:Row(children:[Expanded(child:Text(_status,maxLines:2)),FilledButton.icon(onPressed:_busy?null:_capture,icon:const Icon(Icons.add_location_alt),label:Text(_busy?'Capturing...':'Capture GPS'))])),
      Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Row(children:[OutlinedButton(onPressed:_points.isEmpty?null:()=>_copy(pointsToCsv(_points),'CSV'),child:const Text('Export CSV')),const SizedBox(width:8),OutlinedButton(onPressed:_points.isEmpty?null:()=>_copy(pointsToKml(_points),'KML'),child:const Text('Export KML')),const Spacer(),Text('${_points.length} point(s)') ])),
      Expanded(flex:2,child:_points.isEmpty?const Center(child:Text('No captured points yet')):ListView.builder(itemCount:_points.length,itemBuilder:(c,i){final p=_points[i];return ListTile(dense:true,leading:const Icon(Icons.location_on),title:Text(p.label),subtitle:Text('${p.latitude.toStringAsFixed(7)}, ${p.longitude.toStringAsFixed(7)} · ±${p.accuracyM.toStringAsFixed(1)} m'));}))
    ])
  );
}
$dart$,v_title,v_title);

    v_test := $dart$import 'package:flutter_test/flutter_test.dart';
import 'package:vl_generated_app/field_point.dart';
void main(){
  test('field point JSON roundtrip and exports',(){
    final p=FieldPoint(id:'1',label:'P001',latitude:5.9804,longitude:116.0735,accuracyM:2.5,capturedAt:DateTime.utc(2026,8,26));
    final restored=pointsFromJson(pointsToJson([p])).single;
    expect(restored.latitude,p.latitude); expect(restored.longitude,p.longitude);
    expect(pointsToCsv([p]),contains('P001,5.9804,116.0735'));
    expect(pointsToKml([p]),contains('<coordinates>116.0735,5.9804,0</coordinates>'));
  });
}
$dart$;

    insert into public.generated_artifacts(factory_run_id,project_id,artifact_kind,path,content,sha256,metadata) values
      (new.id,new.project_id,'config','mobile/flutter/pubspec.yaml',v_pubspec,encode(extensions.digest(v_pubspec,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)),
      (new.id,new.project_id,'source','mobile/flutter/lib/field_point.dart',v_model,encode(extensions.digest(v_model,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)),
      (new.id,new.project_id,'source','mobile/flutter/lib/offline_store.dart',v_store,encode(extensions.digest(v_store,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)),
      (new.id,new.project_id,'source','mobile/flutter/lib/main.dart',v_main,encode(extensions.digest(v_main,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)),
      (new.id,new.project_id,'test','mobile/flutter/test/field_point_test.dart',v_test,encode(extensions.digest(v_test,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder))
    on conflict(factory_run_id,path) do nothing;

  elsif v_builder='gis-web-v1' then
    v_main := $ts$import { Map } from 'maplibre-gl';
export function createMap(container:string){return new Map({container,style:'https://demotiles.maplibre.org/style.json',center:[116.0735,5.9804],zoom:10});}
$ts$;
    insert into public.generated_artifacts(factory_run_id,project_id,build_step_id,artifact_kind,path,content,sha256,metadata)
    values(new.id,new.project_id,null,'source','gis/src/map.ts',v_main,encode(extensions.digest(v_main,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)) on conflict(factory_run_id,path) do nothing;
  end if;

  v_manifest := jsonb_pretty(jsonb_build_object('schema','vrs.factory-source-manifest/2','factory_run_id',new.id,'app_spec_id',new.app_spec_id,'builder_key',v_builder,'target_environment',new.target_environment,'production_locked',new.production_locked,'title',a.title,'objective',a.objective,'spec',a.spec));
  insert into public.generated_artifacts(factory_run_id,project_id,build_step_id,artifact_kind,path,content,sha256,metadata)
  values(new.id,new.project_id,null,'manifest','vrs/factory-source-manifest.json',v_manifest,encode(extensions.digest(v_manifest,'sha256'),'hex'),jsonb_build_object('auto_seeded',true,'generator_version','2.0','builder_key',v_builder)) on conflict(factory_run_id,path) do nothing;
  return new;
end;
$function$
;
